# Dockerfile.frontend
FROM node:20

# Install git and pm2
RUN apt-get update && apt-get install -y git && npm install -g pm2

# Declare build arguments
ARG NEXT_PUBLIC_APP_ENV
ARG NEXT_PUBLIC_API_URL_PROD

# Set environment variables for the build
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
ENV NEXT_PUBLIC_API_URL_PROD=${NEXT_PUBLIC_API_URL_PROD}

WORKDIR /app

# Clone frontend and build
RUN git clone https://github.com/kannn044/mtb-frontend.git mtb-frontend
WORKDIR /app/mtb-frontend
RUN npm install
RUN npm run build

# Copy pm2 process file
WORKDIR /app
COPY process.frontend.json .

# Expose port
EXPOSE 3000

# Start service
CMD ["pm2", "start", "process.frontend.json", "--no-daemon"]
