# Dockerfile.backend
FROM node:20

# Install git and pm2
RUN apt-get update && apt-get install -y git && npm install -g pm2

WORKDIR /app

# Clone backend and build
RUN git clone https://github.com/kannn044/mtb-backend.git mtb-backend
WORKDIR /app/mtb-backend
RUN npm install
RUN npm run build

# Copy pm2 process file
WORKDIR /app
COPY process.backend.json .

# Expose port
EXPOSE 3001

# Start service
CMD ["pm2", "start", "process.backend.json", "--no-daemon"]
