name: Update Submodules

on:
  repository_dispatch:
    types: [update_submodules]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mtb-cluster
        uses: actions/checkout@v3
        with:
          repository: 'kannn044/mtb-cluster'
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Update mtb-frontend submodule
        run: |
          git submodule update --remote --merge mtb-frontend

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update mtb-frontend submodule" && git push || echo "No changes to commit"
